/*
Copyright AppsCode Inc. and Contributors

Licensed under the AppsCode Community License 1.0.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://github.com/appscode/licenses/raw/1.0.0/AppsCode-Community-1.0.0.md

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by Kubeform. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"io/ioutil"
	"os"
	"strings"
	"sync"
	"time"

	"github.com/gobuffalo/flect"
	vsphere "github.com/hashicorp/terraform-provider-vsphere/vsphere"
	auditlib "go.bytebuilders.dev/audit/lib"
	arv1 "k8s.io/api/admissionregistration/v1"
	"k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset"
	informers "k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions"
	"k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"
	admissionregistrationv1 "k8s.io/client-go/kubernetes/typed/admissionregistration/v1"
	"k8s.io/client-go/tools/cache"
	"k8s.io/klog/v2"
	computev1alpha1 "kubeform.dev/provider-vsphere-api/apis/compute/v1alpha1"
	contentv1alpha1 "kubeform.dev/provider-vsphere-api/apis/content/v1alpha1"
	customv1alpha1 "kubeform.dev/provider-vsphere-api/apis/custom/v1alpha1"
	datacenterv1alpha1 "kubeform.dev/provider-vsphere-api/apis/datacenter/v1alpha1"
	datastorev1alpha1 "kubeform.dev/provider-vsphere-api/apis/datastore/v1alpha1"
	distributedv1alpha1 "kubeform.dev/provider-vsphere-api/apis/distributed/v1alpha1"
	dpmv1alpha1 "kubeform.dev/provider-vsphere-api/apis/dpm/v1alpha1"
	drsv1alpha1 "kubeform.dev/provider-vsphere-api/apis/drs/v1alpha1"
	entityv1alpha1 "kubeform.dev/provider-vsphere-api/apis/entity/v1alpha1"
	filev1alpha1 "kubeform.dev/provider-vsphere-api/apis/file/v1alpha1"
	folderv1alpha1 "kubeform.dev/provider-vsphere-api/apis/folder/v1alpha1"
	hav1alpha1 "kubeform.dev/provider-vsphere-api/apis/ha/v1alpha1"
	hostv1alpha1 "kubeform.dev/provider-vsphere-api/apis/host/v1alpha1"
	licensev1alpha1 "kubeform.dev/provider-vsphere-api/apis/license/v1alpha1"
	nasv1alpha1 "kubeform.dev/provider-vsphere-api/apis/nas/v1alpha1"
	resourcev1alpha1 "kubeform.dev/provider-vsphere-api/apis/resource/v1alpha1"
	rolev1alpha1 "kubeform.dev/provider-vsphere-api/apis/role/v1alpha1"
	storagev1alpha1 "kubeform.dev/provider-vsphere-api/apis/storage/v1alpha1"
	tagv1alpha1 "kubeform.dev/provider-vsphere-api/apis/tag/v1alpha1"
	vappv1alpha1 "kubeform.dev/provider-vsphere-api/apis/vapp/v1alpha1"
	virtualv1alpha1 "kubeform.dev/provider-vsphere-api/apis/virtual/v1alpha1"
	vmv1alpha1 "kubeform.dev/provider-vsphere-api/apis/vm/v1alpha1"
	vmfsv1alpha1 "kubeform.dev/provider-vsphere-api/apis/vmfs/v1alpha1"
	vnicv1alpha1 "kubeform.dev/provider-vsphere-api/apis/vnic/v1alpha1"
	controllerscompute "kubeform.dev/provider-vsphere-controller/controllers/compute"
	controllerscontent "kubeform.dev/provider-vsphere-controller/controllers/content"
	controllerscustom "kubeform.dev/provider-vsphere-controller/controllers/custom"
	controllersdatacenter "kubeform.dev/provider-vsphere-controller/controllers/datacenter"
	controllersdatastore "kubeform.dev/provider-vsphere-controller/controllers/datastore"
	controllersdistributed "kubeform.dev/provider-vsphere-controller/controllers/distributed"
	controllersdpm "kubeform.dev/provider-vsphere-controller/controllers/dpm"
	controllersdrs "kubeform.dev/provider-vsphere-controller/controllers/drs"
	controllersentity "kubeform.dev/provider-vsphere-controller/controllers/entity"
	controllersfile "kubeform.dev/provider-vsphere-controller/controllers/file"
	controllersfolder "kubeform.dev/provider-vsphere-controller/controllers/folder"
	controllersha "kubeform.dev/provider-vsphere-controller/controllers/ha"
	controllershost "kubeform.dev/provider-vsphere-controller/controllers/host"
	controllerslicense "kubeform.dev/provider-vsphere-controller/controllers/license"
	controllersnas "kubeform.dev/provider-vsphere-controller/controllers/nas"
	controllersresource "kubeform.dev/provider-vsphere-controller/controllers/resource"
	controllersrole "kubeform.dev/provider-vsphere-controller/controllers/role"
	controllersstorage "kubeform.dev/provider-vsphere-controller/controllers/storage"
	controllerstag "kubeform.dev/provider-vsphere-controller/controllers/tag"
	controllersvapp "kubeform.dev/provider-vsphere-controller/controllers/vapp"
	controllersvirtual "kubeform.dev/provider-vsphere-controller/controllers/virtual"
	controllersvm "kubeform.dev/provider-vsphere-controller/controllers/vm"
	controllersvmfs "kubeform.dev/provider-vsphere-controller/controllers/vmfs"
	controllersvnic "kubeform.dev/provider-vsphere-controller/controllers/vnic"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/manager"
)

var _provider = vsphere.Provider()

var runningControllers = struct {
	sync.RWMutex
	mp map[schema.GroupVersionKind]bool
}{mp: make(map[schema.GroupVersionKind]bool)}

func watchCRD(ctx context.Context, crdClient *clientset.Clientset, vwcClient *admissionregistrationv1.AdmissionregistrationV1Client, stopCh <-chan struct{}, mgr manager.Manager, auditor *auditlib.EventPublisher, restrictToNamespace string) error {
	informerFactory := informers.NewSharedInformerFactory(crdClient, time.Second*30)
	i := informerFactory.Apiextensions().V1().CustomResourceDefinitions().Informer()
	l := informerFactory.Apiextensions().V1().CustomResourceDefinitions().Lister()

	i.AddEventHandler(cache.ResourceEventHandlerFuncs{
		AddFunc: func(obj interface{}) {
			var key string
			key, err := cache.MetaNamespaceKeyFunc(obj)
			if err != nil {
				klog.Error(err)
				return
			}

			_, name, err := cache.SplitMetaNamespaceKey(key)
			if err != nil {
				klog.Error(err)
				return
			}

			crd, err := l.Get(name)
			if err != nil {
				klog.Error(err)
				return
			}
			if strings.Contains(crd.Spec.Group, "vsphere.kubeform.com") {
				gvk := schema.GroupVersionKind{
					Group:   crd.Spec.Group,
					Version: crd.Spec.Versions[0].Name,
					Kind:    crd.Spec.Names.Kind,
				}

				// check whether this gvk came before, if no then start the controller
				runningControllers.RLock()
				_, ok := runningControllers.mp[gvk]
				runningControllers.RUnlock()

				if !ok {
					runningControllers.Lock()
					runningControllers.mp[gvk] = true
					runningControllers.Unlock()

					if enableValidatingWebhook {
						// add dynamic ValidatingWebhookConfiguration

						// create empty VWC if the group has come for the first time
						err := createEmptyVWC(vwcClient, gvk)
						if err != nil {
							klog.Error(err)
							return
						}

						// update
						err = updateVWC(vwcClient, gvk)
						if err != nil {
							klog.Error(err)
							return
						}

						err = SetupWebhook(mgr, gvk)
						if err != nil {
							setupLog.Error(err, "unable to enable webhook")
							os.Exit(1)
						}
					}

					err = SetupManager(ctx, mgr, gvk, auditor, restrictToNamespace)
					if err != nil {
						setupLog.Error(err, "unable to start manager")
						os.Exit(1)
					}
				}
			}
		},
	})

	informerFactory.Start(stopCh)

	return nil
}

func createEmptyVWC(vwcClient *admissionregistrationv1.AdmissionregistrationV1Client, gvk schema.GroupVersionKind) error {
	vwcName := strings.ReplaceAll(strings.ToLower(gvk.Group), ".", "-")
	_, err := vwcClient.ValidatingWebhookConfigurations().Get(context.TODO(), vwcName, metav1.GetOptions{})
	if err == nil || !(errors.IsNotFound(err)) {
		return err
	}

	emptyVWC := &arv1.ValidatingWebhookConfiguration{
		TypeMeta: metav1.TypeMeta{
			Kind:       "ValidatingWebhookConfiguration",
			APIVersion: "admissionregistration.k8s.io/v1",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name: strings.ReplaceAll(strings.ToLower(gvk.Group), ".", "-"),
			Labels: map[string]string{
				"app.kubernetes.io/instance": "vsphere.kubeform.com",
				"app.kubernetes.io/part-of":  "kubeform.com",
			},
		},
	}
	_, err = vwcClient.ValidatingWebhookConfigurations().Create(context.TODO(), emptyVWC, metav1.CreateOptions{})
	if err != nil {
		return err
	}

	return nil
}

func updateVWC(vwcClient *admissionregistrationv1.AdmissionregistrationV1Client, gvk schema.GroupVersionKind) error {
	vwcName := strings.ReplaceAll(strings.ToLower(gvk.Group), ".", "-")
	vwc, err := vwcClient.ValidatingWebhookConfigurations().Get(context.TODO(), vwcName, metav1.GetOptions{})
	if err != nil {
		return err
	}

	path := "/validate-" + strings.ReplaceAll(strings.ToLower(gvk.Group), ".", "-") + "-v1alpha1-" + strings.ToLower(gvk.Kind)
	fail := arv1.Fail
	sideEffects := arv1.SideEffectClassNone
	admissionReviewVersions := []string{"v1beta1"}

	rules := []arv1.RuleWithOperations{
		{
			Operations: []arv1.OperationType{
				arv1.Delete,
				arv1.Update,
			},
			Rule: arv1.Rule{
				APIGroups:   []string{strings.ToLower(gvk.Group)},
				APIVersions: []string{gvk.Version},
				Resources:   []string{strings.ToLower(flect.Pluralize(gvk.Kind))},
			},
		},
	}

	data, err := ioutil.ReadFile("/tmp/k8s-webhook-server/serving-certs/ca.crt")
	if err != nil {
		return err
	}

	name := strings.ToLower(gvk.Kind) + "." + gvk.Group
	for _, webhook := range vwc.Webhooks {
		if webhook.Name == name {
			return nil
		}
	}

	newWebhook := arv1.ValidatingWebhook{
		Name: name,
		ClientConfig: arv1.WebhookClientConfig{
			Service: &arv1.ServiceReference{
				Namespace: webhookNamespace,
				Name:      webhookName,
				Path:      &path,
			},
			CABundle: data,
		},
		Rules:                   rules,
		FailurePolicy:           &fail,
		SideEffects:             &sideEffects,
		AdmissionReviewVersions: admissionReviewVersions,
	}

	vwc.Webhooks = append(vwc.Webhooks, newWebhook)

	_, err = vwcClient.ValidatingWebhookConfigurations().Update(context.TODO(), vwc, metav1.UpdateOptions{})
	if err != nil {
		return err
	}

	return nil
}

func SetupManager(ctx context.Context, mgr manager.Manager, gvk schema.GroupVersionKind, auditor *auditlib.EventPublisher, restrictToNamespace string) error {
	switch gvk {
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Cluster",
	}:
		if err := (&controllerscompute.ClusterReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Cluster"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_compute_cluster"],
			TypeName: "vsphere_compute_cluster",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Cluster")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterHostGroup",
	}:
		if err := (&controllerscompute.ClusterHostGroupReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("ClusterHostGroup"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_compute_cluster_host_group"],
			TypeName: "vsphere_compute_cluster_host_group",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "ClusterHostGroup")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmAffinityRule",
	}:
		if err := (&controllerscompute.ClusterVmAffinityRuleReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("ClusterVmAffinityRule"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_compute_cluster_vm_affinity_rule"],
			TypeName: "vsphere_compute_cluster_vm_affinity_rule",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "ClusterVmAffinityRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmAntiAffinityRule",
	}:
		if err := (&controllerscompute.ClusterVmAntiAffinityRuleReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("ClusterVmAntiAffinityRule"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_compute_cluster_vm_anti_affinity_rule"],
			TypeName: "vsphere_compute_cluster_vm_anti_affinity_rule",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "ClusterVmAntiAffinityRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmDependencyRule",
	}:
		if err := (&controllerscompute.ClusterVmDependencyRuleReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("ClusterVmDependencyRule"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_compute_cluster_vm_dependency_rule"],
			TypeName: "vsphere_compute_cluster_vm_dependency_rule",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "ClusterVmDependencyRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmGroup",
	}:
		if err := (&controllerscompute.ClusterVmGroupReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("ClusterVmGroup"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_compute_cluster_vm_group"],
			TypeName: "vsphere_compute_cluster_vm_group",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "ClusterVmGroup")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmHostRule",
	}:
		if err := (&controllerscompute.ClusterVmHostRuleReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("ClusterVmHostRule"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_compute_cluster_vm_host_rule"],
			TypeName: "vsphere_compute_cluster_vm_host_rule",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "ClusterVmHostRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "content.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Library",
	}:
		if err := (&controllerscontent.LibraryReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Library"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_content_library"],
			TypeName: "vsphere_content_library",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Library")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "content.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "LibraryItem",
	}:
		if err := (&controllerscontent.LibraryItemReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("LibraryItem"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_content_library_item"],
			TypeName: "vsphere_content_library_item",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "LibraryItem")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "custom.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Attribute",
	}:
		if err := (&controllerscustom.AttributeReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Attribute"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_custom_attribute"],
			TypeName: "vsphere_custom_attribute",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Attribute")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "datacenter.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Datacenter",
	}:
		if err := (&controllersdatacenter.DatacenterReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Datacenter"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_datacenter"],
			TypeName: "vsphere_datacenter",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Datacenter")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "datastore.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Cluster",
	}:
		if err := (&controllersdatastore.ClusterReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Cluster"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_datastore_cluster"],
			TypeName: "vsphere_datastore_cluster",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Cluster")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "datastore.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmAntiAffinityRule",
	}:
		if err := (&controllersdatastore.ClusterVmAntiAffinityRuleReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("ClusterVmAntiAffinityRule"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_datastore_cluster_vm_anti_affinity_rule"],
			TypeName: "vsphere_datastore_cluster_vm_anti_affinity_rule",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "ClusterVmAntiAffinityRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "distributed.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "PortGroup",
	}:
		if err := (&controllersdistributed.PortGroupReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("PortGroup"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_distributed_port_group"],
			TypeName: "vsphere_distributed_port_group",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "PortGroup")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "distributed.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "VirtualSwitch",
	}:
		if err := (&controllersdistributed.VirtualSwitchReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("VirtualSwitch"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_distributed_virtual_switch"],
			TypeName: "vsphere_distributed_virtual_switch",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "VirtualSwitch")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "dpm.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "HostOverride",
	}:
		if err := (&controllersdpm.HostOverrideReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("HostOverride"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_dpm_host_override"],
			TypeName: "vsphere_dpm_host_override",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "HostOverride")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "drs.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "VmOverride",
	}:
		if err := (&controllersdrs.VmOverrideReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("VmOverride"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_drs_vm_override"],
			TypeName: "vsphere_drs_vm_override",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "VmOverride")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "entity.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Permissions",
	}:
		if err := (&controllersentity.PermissionsReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Permissions"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_entity_permissions"],
			TypeName: "vsphere_entity_permissions",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Permissions")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "file.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "File",
	}:
		if err := (&controllersfile.FileReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("File"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_file"],
			TypeName: "vsphere_file",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "File")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "folder.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Folder",
	}:
		if err := (&controllersfolder.FolderReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Folder"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_folder"],
			TypeName: "vsphere_folder",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Folder")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "ha.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "VmOverride",
	}:
		if err := (&controllersha.VmOverrideReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("VmOverride"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_ha_vm_override"],
			TypeName: "vsphere_ha_vm_override",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "VmOverride")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "host.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Host",
	}:
		if err := (&controllershost.HostReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Host"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_host"],
			TypeName: "vsphere_host",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Host")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "host.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "PortGroup",
	}:
		if err := (&controllershost.PortGroupReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("PortGroup"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_host_port_group"],
			TypeName: "vsphere_host_port_group",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "PortGroup")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "host.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "VirtualSwitch",
	}:
		if err := (&controllershost.VirtualSwitchReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("VirtualSwitch"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_host_virtual_switch"],
			TypeName: "vsphere_host_virtual_switch",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "VirtualSwitch")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "license.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "License",
	}:
		if err := (&controllerslicense.LicenseReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("License"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_license"],
			TypeName: "vsphere_license",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "License")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "nas.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Datastore",
	}:
		if err := (&controllersnas.DatastoreReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Datastore"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_nas_datastore"],
			TypeName: "vsphere_nas_datastore",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Datastore")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "resource.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Pool",
	}:
		if err := (&controllersresource.PoolReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Pool"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_resource_pool"],
			TypeName: "vsphere_resource_pool",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Pool")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "role.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Role",
	}:
		if err := (&controllersrole.RoleReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Role"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_role"],
			TypeName: "vsphere_role",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Role")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "storage.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "DrsVmOverride",
	}:
		if err := (&controllersstorage.DrsVmOverrideReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("DrsVmOverride"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_storage_drs_vm_override"],
			TypeName: "vsphere_storage_drs_vm_override",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "DrsVmOverride")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "tag.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Tag",
	}:
		if err := (&controllerstag.TagReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Tag"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_tag"],
			TypeName: "vsphere_tag",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Tag")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "tag.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Category",
	}:
		if err := (&controllerstag.CategoryReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Category"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_tag_category"],
			TypeName: "vsphere_tag_category",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Category")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vapp.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Container",
	}:
		if err := (&controllersvapp.ContainerReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Container"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_vapp_container"],
			TypeName: "vsphere_vapp_container",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Container")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vapp.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Entity",
	}:
		if err := (&controllersvapp.EntityReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Entity"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_vapp_entity"],
			TypeName: "vsphere_vapp_entity",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Entity")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "virtual.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Disk",
	}:
		if err := (&controllersvirtual.DiskReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Disk"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_virtual_disk"],
			TypeName: "vsphere_virtual_disk",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Disk")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "virtual.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Machine",
	}:
		if err := (&controllersvirtual.MachineReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Machine"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_virtual_machine"],
			TypeName: "vsphere_virtual_machine",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Machine")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "virtual.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "MachineSnapshot",
	}:
		if err := (&controllersvirtual.MachineSnapshotReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("MachineSnapshot"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_virtual_machine_snapshot"],
			TypeName: "vsphere_virtual_machine_snapshot",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "MachineSnapshot")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vm.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "StoragePolicy",
	}:
		if err := (&controllersvm.StoragePolicyReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("StoragePolicy"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_vm_storage_policy"],
			TypeName: "vsphere_vm_storage_policy",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "StoragePolicy")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vmfs.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Datastore",
	}:
		if err := (&controllersvmfs.DatastoreReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Datastore"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_vmfs_datastore"],
			TypeName: "vsphere_vmfs_datastore",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Datastore")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vnic.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Vnic",
	}:
		if err := (&controllersvnic.VnicReconciler{
			Client:   mgr.GetClient(),
			Log:      ctrl.Log.WithName("controllers").WithName("Vnic"),
			Scheme:   mgr.GetScheme(),
			Gvk:      gvk,
			Provider: _provider,
			Resource: _provider.ResourcesMap["vsphere_vnic"],
			TypeName: "vsphere_vnic",
		}).SetupWithManager(ctx, mgr, auditor, restrictToNamespace); err != nil {
			setupLog.Error(err, "unable to create controller", "controller", "Vnic")
			return err
		}

	default:
		return fmt.Errorf("Invalid CRD")
	}

	return nil
}

func SetupWebhook(mgr manager.Manager, gvk schema.GroupVersionKind) error {
	switch gvk {
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Cluster",
	}:
		if err := (&computev1alpha1.Cluster{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Cluster")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterHostGroup",
	}:
		if err := (&computev1alpha1.ClusterHostGroup{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "ClusterHostGroup")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmAffinityRule",
	}:
		if err := (&computev1alpha1.ClusterVmAffinityRule{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "ClusterVmAffinityRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmAntiAffinityRule",
	}:
		if err := (&computev1alpha1.ClusterVmAntiAffinityRule{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "ClusterVmAntiAffinityRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmDependencyRule",
	}:
		if err := (&computev1alpha1.ClusterVmDependencyRule{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "ClusterVmDependencyRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmGroup",
	}:
		if err := (&computev1alpha1.ClusterVmGroup{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "ClusterVmGroup")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "compute.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmHostRule",
	}:
		if err := (&computev1alpha1.ClusterVmHostRule{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "ClusterVmHostRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "content.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Library",
	}:
		if err := (&contentv1alpha1.Library{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Library")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "content.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "LibraryItem",
	}:
		if err := (&contentv1alpha1.LibraryItem{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "LibraryItem")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "custom.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Attribute",
	}:
		if err := (&customv1alpha1.Attribute{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Attribute")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "datacenter.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Datacenter",
	}:
		if err := (&datacenterv1alpha1.Datacenter{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Datacenter")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "datastore.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Cluster",
	}:
		if err := (&datastorev1alpha1.Cluster{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Cluster")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "datastore.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "ClusterVmAntiAffinityRule",
	}:
		if err := (&datastorev1alpha1.ClusterVmAntiAffinityRule{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "ClusterVmAntiAffinityRule")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "distributed.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "PortGroup",
	}:
		if err := (&distributedv1alpha1.PortGroup{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "PortGroup")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "distributed.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "VirtualSwitch",
	}:
		if err := (&distributedv1alpha1.VirtualSwitch{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "VirtualSwitch")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "dpm.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "HostOverride",
	}:
		if err := (&dpmv1alpha1.HostOverride{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "HostOverride")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "drs.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "VmOverride",
	}:
		if err := (&drsv1alpha1.VmOverride{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "VmOverride")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "entity.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Permissions",
	}:
		if err := (&entityv1alpha1.Permissions{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Permissions")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "file.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "File",
	}:
		if err := (&filev1alpha1.File{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "File")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "folder.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Folder",
	}:
		if err := (&folderv1alpha1.Folder{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Folder")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "ha.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "VmOverride",
	}:
		if err := (&hav1alpha1.VmOverride{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "VmOverride")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "host.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Host",
	}:
		if err := (&hostv1alpha1.Host{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Host")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "host.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "PortGroup",
	}:
		if err := (&hostv1alpha1.PortGroup{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "PortGroup")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "host.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "VirtualSwitch",
	}:
		if err := (&hostv1alpha1.VirtualSwitch{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "VirtualSwitch")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "license.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "License",
	}:
		if err := (&licensev1alpha1.License{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "License")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "nas.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Datastore",
	}:
		if err := (&nasv1alpha1.Datastore{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Datastore")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "resource.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Pool",
	}:
		if err := (&resourcev1alpha1.Pool{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Pool")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "role.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Role",
	}:
		if err := (&rolev1alpha1.Role{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Role")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "storage.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "DrsVmOverride",
	}:
		if err := (&storagev1alpha1.DrsVmOverride{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "DrsVmOverride")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "tag.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Tag",
	}:
		if err := (&tagv1alpha1.Tag{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Tag")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "tag.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Category",
	}:
		if err := (&tagv1alpha1.Category{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Category")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vapp.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Container",
	}:
		if err := (&vappv1alpha1.Container{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Container")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vapp.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Entity",
	}:
		if err := (&vappv1alpha1.Entity{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Entity")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "virtual.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Disk",
	}:
		if err := (&virtualv1alpha1.Disk{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Disk")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "virtual.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Machine",
	}:
		if err := (&virtualv1alpha1.Machine{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Machine")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "virtual.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "MachineSnapshot",
	}:
		if err := (&virtualv1alpha1.MachineSnapshot{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "MachineSnapshot")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vm.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "StoragePolicy",
	}:
		if err := (&vmv1alpha1.StoragePolicy{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "StoragePolicy")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vmfs.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Datastore",
	}:
		if err := (&vmfsv1alpha1.Datastore{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Datastore")
			return err
		}
	case schema.GroupVersionKind{
		Group:   "vnic.vsphere.kubeform.com",
		Version: "v1alpha1",
		Kind:    "Vnic",
	}:
		if err := (&vnicv1alpha1.Vnic{}).SetupWebhookWithManager(mgr); err != nil {
			setupLog.Error(err, "unable to create webhook", "webhook", "Vnic")
			return err
		}

	default:
		return fmt.Errorf("Invalid Webhook")
	}

	return nil
}
